---
title: "Figures"
author: "B. Raynor"
date: "3/16/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path="figure")


library(dplyr)
library(ggplot2)
```

## SUB-OPTIMAL VACCINATION
```{r, warning=FALSE, message=FALSE,fig.width=12}

load(here::here("data_simulated", "Sims_03-26_LowVac.Rda"))
df <-out

#add dates
start <- as.Date("2016-01-01")
end <- as.Date("2021-12-30")
df.dates <- data.frame(Date = seq(start, end, "days"), 
                       time = seq(1:(max(df$time)+1))-1)
df <-left_join(df, df.dates, multiple = "all")

df$month <- format(df$Date,"%m")
df$year <- format(df$Date,"%Y")

max_prevalence = 0.005
#max_prevalence = 0.0015

df2 <-df
df2 <- df %>%
  filter(time > (365*2))

#only need infected, prevalence and indicators
df2$N <- df2%>%select(S1:V20) %>%
  rowSums()
df2$I <- df2%>%select(I1:I20)%>%
  rowSums()
# df2 <- df2%>%
#   mutate(prev = I/N)


#avg sims
df2 <- df2%>%
  select(time, Date, month, year, beta, beta.contact, I, N, sim)%>%
  group_by(time, Date, month, year, beta, beta.contact)%>%
  summarise(SI_2.5 = quantile(I, .025),
            SI_97.5 = quantile(I, .975),
            I = mean(I),
            N= mean(N))%>%
  mutate(prev = I/N)

#Make sure prevalence stays low
prev <- df2 %>% 
  group_by(beta, beta.contact)%>%
  summarise(max_prev = max(prev))%>%
  filter(max_prev < max_prevalence)%>%
  select(-max_prev)


df2 <- left_join(prev, df2, multiple = "all")

#make sure disease is persistant
pers <- df2%>%
  filter(Date == end,
         I > 0)%>%
  select(beta, beta.contact)
df2 <- left_join(pers, df2, multiple = "all")

pers

#Visualize
df2 <- df2 %>% 
  mutate(id = paste0(beta, ", ", beta.contact))%>%
  mutate(prev= ifelse(prev==0, NA, prev))

ggplot()+
  theme_classic()+
  geom_ribbon(data=df2, aes(x=Date, ymin = SI_2.5/N, ymax = SI_97.5/N, group=id), fill = "grey70") +
    geom_line(data=df2, aes(x=Date, y=I/N, group=id), size=1)+
  theme(text = element_text(size=20), axis.text.x = element_text(size=16), axis.text.y = element_text(size=16))+
  ylab("Infected Counts") + ggtitle("Sub-optimal vaccination")

ggplot()+
  theme_classic()+
  geom_line(data=df2, aes(x=Date, y=prev, group=id))+
  theme(text = element_text(size=20), axis.text.x = element_text(size=16), axis.text.y = element_text(size=16))+
  ylab("Prevalence") + ggtitle("Sub-optimal vaccination")

```




## OPTIMAL VACCINATION COVERAGE


```{r, fig.width=12, warning=FALSE, message=FALSE}
load(here::here("data_simulated", "Sims_03-26_HighVac.Rda"))
df2 <- out

start <- as.Date("2016-01-01")
end <- as.Date("2021-12-30")

df.dates <- data.frame(Date = seq(start, end, "days"), 
                       time = seq(1:(max(df2$time)+1))-1)

df2 <-left_join(df2, df.dates)

df2$month <- format(df2$Date,"%m")
df2$year <- format(df2$Date,"%Y")

#only need infected, prevalence and indicators
df2$N <- df2%>%select(S1:V20) %>%
  rowSums()
df2$I <- df2%>%select(I1:I20)%>%
  rowSums()
# df2 <- df2%>%
#   mutate(prev = I/N)

#avg sims
df2 <- df2%>%
  select(time, Date, month, year, beta, beta.contact, I, N, sim)%>%
  group_by(time, Date, month, year, beta, beta.contact)%>%
  summarise(SI_2.5 = quantile(I, .025),
            SI_97.5 = quantile(I, .975),
            I = mean(I),
            N= mean(N))%>%
  mutate(prev = I/N)

#make sure disease is eliminated
pers <- df2%>%
  filter(Date == end,
         I == 0)%>%
  as.data.frame()

pers<- pers%>%
  select(beta, beta.contact)

df2 <- left_join(pers, df2)


df2 <- df2 %>% 
  mutate(id = paste0(beta, ", ", beta.contact))%>%
  mutate(prev= ifelse(prev==0, NA, prev))

unique(df2$id)

ggplot()+
  theme_classic()+
  geom_ribbon(data=df2, aes(x=Date, ymin = SI_2.5/N, ymax = SI_97.5/N, group=id), fill = "grey70") +
    geom_line(data=df2, aes(x=Date, y=I/N, group=id), size=1)+
  theme(text = element_text(size=20), axis.text.x = element_text(size=16), axis.text.y = element_text(size=16))+
  ylab("Infected Counts") + ggtitle("Optimal vaccination")


ggplot()+
  theme_classic()+
  geom_line(data=df2, aes(x=Date, y=prev, group=id))+
  theme(text = element_text(size=20), axis.text.x = element_text(size=16), axis.text.y = element_text(size=16))+
  ylab("Prevalence") + ggtitle("Optimal vaccination")
```



## HISTORIC FIT

```{r, warning=FALSE, message=FALSE}
set.seed(123)

#load historical and simualted data to compare
df.data <- readRDS(here::here("data_minimal", "Cases.Rda")) #real cases 2016 - 2021
load(here::here("data_simulated", "Sims_03-26_HistVac.Rda")) #historic simulation runs
load(here::here("data_minimal", "df.MR.parms.Rda")) 
df.d <- data.frame(microred=df.MR.parms$microred, #proportions from bayes analysis
                   prop = c(0.02, 0.02, 0.02,0.05,
                            0.02, 0.02, 0.02,0.05,
                            0.05, 0.02, 0.05, 0.02,
                            0, 0.01, 0, 0.62, 0.62,
                            0.01, 0.62, 0.62))
#distribute proportions so mean = 0.1
df.d <- df.d %>%
  mutate(prob = prop*(0.1))

#only need indicators of sim incidence
df3 <- out
df3 <- df3%>%
  select(time, sim, beta, beta.contact, X1:X20)

#detection rate by microred
df3 <- df3 %>%
  mutate(X1 = rbinom(length(time), size=floor(X1), prob =df.d[1,3]),
         X2 = rbinom(length(time), size=floor(X2), prob =df.d[2,3]),
         X3 = rbinom(length(time), size=floor(X3), prob =df.d[3,3]),
         X4 = rbinom(length(time), size=floor(X4), prob =df.d[4,3]),
         X5 = rbinom(length(time), size=floor(X5), prob =df.d[5,3]),
         X6 = rbinom(length(time), size=floor(X6), prob =df.d[6,3]),
         X7 = rbinom(length(time), size=floor(X7), prob =df.d[7,3]),
         X8 = rbinom(length(time), size=floor(X8), prob =df.d[8,3]),
         X9 = rbinom(length(time), size=floor(X9), prob =df.d[9,3]),
         X10 = rbinom(length(time), size=floor(X10), prob =df.d[10,3]),
         X11 = rbinom(length(time), size=floor(X11), prob =df.d[11,3]),
         X12 = rbinom(length(time), size=floor(X12), prob =df.d[12,3]),
         X13 = rbinom(length(time), size=floor(X13), prob =df.d[13,3]),
         X14 = rbinom(length(time), size=floor(X14), prob =df.d[14,3]),
         X15 = rbinom(length(time), size=floor(X15), prob =df.d[15,3]),
         X16 = rbinom(length(time), size=floor(X16), prob =df.d[16,3]),
         X17 = rbinom(length(time), size=floor(X17), prob =df.d[17,3]),
         X18 = rbinom(length(time), size=floor(X18), prob =df.d[18,3]),
         X19 = rbinom(length(time), size=floor(X19), prob =df.d[19,3]),
         X20 = rbinom(length(time), size=floor(X20), prob =df.d[20,3]))

#aggregate to months
#add in date
start <- as.Date("2016-01-01")
end <- as.Date("2021-12-30")
df.dates <- data.frame(Date = seq(start, end, "days"), 
                       time = seq(1:(max(df3$time)+1))-1)
df3 <-left_join(df3, df.dates)
df3$month <- format(df3$Date,"%m")
df3$year <- format(df3$Date,"%Y")

df3$X <- df3%>%select(X1:X20) %>%
  rowSums()

df3 <- df3 %>% 
  mutate(id = paste0(beta, ", ", beta.contact))

#aggregate by month
df.m <- df3 %>%
  group_by(beta, beta.contact, sim, year, month)%>%
  summarise(X = sum(X))

#find mean case counts
df.m <- df.m%>%
  group_by(beta, beta.contact, year, month)%>%
  summarise(SI_2.5 = quantile(X, .025),
            SI_97.5 = quantile(X, .975),
            X = round(mean(X)))

#filter to 2018+
df.m <- df.m%>%
  filter(year == "2017" | year == "2018" | year == "2019")
  
df.comp <- left_join(df.m, df.data) %>%
  rename(cases_sim=X)


```

Least squares for whole city
```{r, fig.width=12, warning=FALSE, message=FALSE}
#aggregate to full city
df.comp <- df.comp %>%
  mutate(diff.sq = (cases_sim - cases_obs)^2) #calculate squared diff between obs and sim


#run least sq
df.LS <- df.comp %>%
  group_by(beta, beta.contact) %>%
  summarise(SumSq = sum(diff.sq))%>%
  as.data.frame()

result <- df.LS %>%
  filter(SumSq == min(SumSq))
result

df.comp3 <- df.comp%>%
  filter(beta == result$beta[1],
         beta.contact==result$beta.contact[1])%>%
  rename(simulated = cases_sim, observed= cases_obs)%>%
  arrange(year)


df.comp3$Month <- seq(1:length(df.comp3$beta)) 

df.comp3 <- df.comp3%>% 
  tidyr::pivot_longer(
    cols = `simulated`:`observed`, 
    names_to = "Case_type",
    values_to = "Case_number"
)%>%
  mutate(SI_2.5 = ifelse(Case_type == "observed", NA, SI_2.5),
         SI_97.5 = ifelse(Case_type == "observed", NA, SI_97.5),)

ggplot()+
  theme_classic()+
  geom_col(data=df.comp3, aes(x=Month, y=Case_number, fill=Case_type), position='dodge')+
  geom_errorbar(data = df.comp3, aes(x=Month, ymin = SI_2.5, ymax = SI_97.5))+
  theme(text = element_text(size=20), axis.text.x = element_text(size=16), axis.text.y = element_text(size=16))+
  theme(legend.position = "none")+
  ylab("Reported cases") + ggtitle("Best fit")

```
